### ISSUE TITLE
Interview Katie

### ISSUE THREAD

**Issue by stew0343** [MTM6330-F18/final-ssass#10]

**Comment by steffensen** [comment]
Katie Tremblay 
Age: 30

1 a. How long have you been teaching at Algonquin College? 
7 years - Jan 2012 

1 b. How man years in IMD?
4 Years IMD Fall 2015

2 a. Which courses have you taught at Algonquin?
- Studio Lab
- Studio Lab 2
- Client Projects
- Video Foundation
- Motion Graphics 
- UX Design
- Dynamic Media 
- Design & Authoring 

2 b. Which course do you prefer teaching?
I prefer teaching Dynamic Media because I love animation and action script 3.0

3. What previous schooling do you have?
Communications @ University of Ottawa - 2010 April
Interactive Media Managment - 2011 April 

4. What's your favorite hobby to do outside of class?
Volleyball - I enjoy being active.

5. If you could give a future IMD student one piece of advice what would it be?
Be open to all the courses, don't narrow your focus till you've tried everything.
